// apps/app/src/components/MessageItem/index.tsx
import { GlobeIcon, SearchIcon } from 'lucide-react';
import { useState } from 'react';
import Markdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

import { cn } from '@/lib/utils';
import type { ChatMessage, WebsearchResult } from '@chaptale/shared';

import 'github-markdown-css/github-markdown.css';
import styles from './MessageItem.module.scss';

export type MessageItemProps = {
  message: ChatMessage;
};

export function MessageItem(props: MessageItemProps) {
  const { message } = props;

  const isUserMessage = message.type === 'user';

  return (
    <div className={cn(styles.messageContainer, isUserMessage && styles.messageContainerUser)}>
      {isUserMessage && <UserMessage {...message.payload} />}

      {message.type === 'assistant' && <AssistantMessage {...message.payload} />}

      {message.type === 'tool_call' && message.payload.name === 'websearch' && <ToolCallMessage {...message.payload} />}

      {message.type === 'tool_result' && <ToolResultMessage {...message.payload} />}
    </div>
  );
}

function UserMessage(props: { content: string }) {
  const { content } = props;

  return <p className={styles.userMessage}>{content}</p>;
}

function AssistantMessage(props: { content: string }) {
  const { content } = props;

  return (
    <div className='markdown-body'>
      <Markdown remarkPlugins={[remarkGfm]}>{content}</Markdown>
    </div>
  );
}

function ToolCallMessage(props: { id: string; name: string; args: Record<string, any> }) {
  const { name, args } = props;

  if (name === 'websearch') {
    return <WebsearchKeywordsMessage keywords={args.keywords} />;
  }

  // TODO: 其他工具调用展示

  return null;
}

function ToolResultMessage(props: { tool_call_id: string; name: string; content: string }) {
  const { name, content } = props;

  if (name === 'websearch') {
    return <WebsearchResultsMessage searchResults={JSON.parse(content) as WebsearchResult} />;
  }

  // TODO: 其他工具结果展示

  return null;
}

function WebsearchKeywordsMessage(props: { keywords: string }) {
  const { keywords } = props;

  return (
    <div className={styles.websearchKeywords}>
      <SearchIcon className={styles.websearchKeywordsIcon} size={18} />
      <span className={styles.websearchKeywordsText}>
        正在搜索：
        <span className={styles.websearchKeywordsQuery}>{keywords}</span>
      </span>
    </div>
  );
}

function WebsearchResultsMessage(props: { searchResults: WebsearchResult }) {
  const { searchResults } = props;

  const [showAll, setShowAll] = useState(false);

  const displayedResults = showAll ? searchResults : searchResults.slice(0, 5);

  return (
    <div className={styles.websearchResults}>
      {/* 结果标题 */}
      <p className={styles.websearchResultsHeader}>
        <GlobeIcon size={18} />
        已搜索 {searchResults.length} 条结果
      </p>

      {/* 结果列表 */}
      <div className={styles.resultsList}>
        {displayedResults.map((result, index) => (
          <a key={index} className={styles.resultItem} href={result.link} target='_blank'>
            <p className={styles.resultTitle}>{result.title}</p>
            <p className={styles.resultDescription}>{result.description}</p>
          </a>
        ))}
      </div>

      {/* 展开、收起 */}
      <div className={styles.toggleButton}>
        <span className={styles.toggleButtonText} onClick={() => setShowAll(!showAll)}>
          {showAll ? '收起' : '展开所有'}
        </span>
      </div>
    </div>
  );
}

// apps/app/src/components/MessageItem/index.vue
<script setup lang="ts">
import MarkdownIt from 'markdown-it';
import { computed, ref } from 'vue';

import type { ChatMessage, WebsearchResult } from '@chaptale/shared';
import { cn } from '@/lib/utils';

import 'github-markdown-css/github-markdown.css';
import styles from './MessageItem.module.scss';

const props = defineProps<{
  message: ChatMessage;
}>();

const markdown = new MarkdownIt({
  html: false,
  linkify: true,
  breaks: true
});

const showAll = ref(false);
const isUserMessage = computed(() => props.message.type === 'user');
const assistantHtml = computed(() => {
  if (props.message.type !== 'assistant') return '';

  return markdown.render(props.message.payload.content);
});

const websearchResults = computed<WebsearchResult>(() => {
  if (props.message.type !== 'tool_result' || props.message.payload.name !== 'websearch') return [];

  try {
    return JSON.parse(props.message.payload.content) as WebsearchResult;
  } catch {
    return [];
  }
});

const displayedResults = computed(() => {
  return showAll.value ? websearchResults.value : websearchResults.value.slice(0, 5);
});
</script>

<template>
  <div :class="cn(styles.messageContainer, isUserMessage && styles.messageContainerUser)">
    <p v-if="message.type === 'user'" :class="styles.userMessage">{{ message.payload.content }}</p>

    <div v-else-if="message.type === 'assistant'" class="markdown-body" v-html="assistantHtml" />

    <div
      v-else-if="message.type === 'tool_call' && message.payload.name === 'websearch'"
      :class="styles.websearchKeywords"
    >
      <span :class="styles.websearchKeywordsIcon" aria-hidden="true">⌕</span>
      <span :class="styles.websearchKeywordsText">
        正在搜索：
        <span :class="styles.websearchKeywordsQuery">{{ message.payload.args.keywords }}</span>
      </span>
    </div>

    <div
      v-else-if="message.type === 'tool_result' && message.payload.name === 'websearch'"
      :class="styles.websearchResults"
    >
      <p :class="styles.websearchResultsHeader">
        <span aria-hidden="true">◎</span>
        已搜索 {{ websearchResults.length }} 条结果
      </p>

      <div :class="styles.resultsList">
        <a
          v-for="(result, index) in displayedResults"
          :key="index"
          :class="styles.resultItem"
          :href="result.link"
          target="_blank"
          rel="noreferrer"
        >
          <p :class="styles.resultTitle">{{ result.title }}</p>
          <p :class="styles.resultDescription">{{ result.description }}</p>
        </a>
      </div>

      <div :class="styles.toggleButton">
        <span :class="styles.toggleButtonText" @click="showAll = !showAll">
          {{ showAll ? '收起' : '展开所有' }}
        </span>
      </div>
    </div>
  </div>
</template>
